workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play # <-- (Optional) if you plan to publish to Google Play
      vars:
        PACKAGE_NAME: "com.fintrack.app" # <-- Replace with your actual package name
        GOOGLE_PLAY_TRACK: "internal" # <-- Options: internal, alpha, beta, production
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.daemon=false"
        _JAVA_OPTIONS: "-Xmx2048m"
      java: 11
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze
      
      - name: Flutter unit tests
        script: |
          flutter test
          
      - name: Build APK with Flutter
        script: |
          flutter build apk --debug --dart-define=flutter.inspector.structuredErrors=false
          
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      # Uncomment below if you want to publish to Google Play automatically
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fintrack.app # <-- Replace with your bundle ID
      vars:
        BUNDLE_ID: "com.fintrack.app" # <-- Replace with your bundle ID
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter analyze
        script: |
          flutter analyze
      
      - name: Flutter unit tests
        script: |
          flutter test
      
      - name: Flutter build
        script: |
          flutter build ios --release --no-codesign
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # Uncomment below if you want to publish to App Store automatically
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
      #   beta_groups:
      #     - group name 1
      #     - group name 2
