name: fintrack
description: A simple accounting app
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter